plugins {
    alias(libs.plugins.kotlin.jvm)
    `java-gradle-plugin`
    id("cucumberkmp.publishing")
}

kotlin {
    explicitApi()
    jvmToolchain(21)
}

// Central requires a sources jar; java-gradle-plugin does not add one. It attaches to the
// `pluginMaven` publication, not to the plugin marker, which is correct — a marker is POM-only.
java {
    withSourcesJar()
}

dependencies {
    implementation(libs.kotlinpoet)

    // The plugin parses .feature files during the build with the very same parser the runtime
    // uses, so there is exactly one Gherkin implementation in the project. This is the JVM
    // artifact of a multiplatform module. See ARCHITECTURE.md §12.4.
    implementation(project(":cucumber-kmp-core"))

    // Needed to register the generated directory with each target's test source set.
    compileOnly(libs.plugin.kotlin)

    // Needed to hand KSP the package to generate the step registry into. compileOnly for the same
    // reason as the Kotlin plugin: a consumer using only the `steps { }` DSL never applies KSP.
    compileOnly(libs.plugin.ksp)

    testImplementation(kotlin("test"))
    testImplementation(gradleTestKit())
}

// The plugin adds `cucumber-kmp-ksp` to consumers itself, so it has to know its own version.
// Generated rather than hardcoded, for the same reason the example reads gradle.properties: a
// release must not be able to leave a version behind.
val generateVersionConstant = tasks.register("generateVersionConstant") {
    val outputDir = layout.buildDirectory.dir("generated/version/kotlin")
    val pluginVersion = project.version.toString()
    inputs.property("version", pluginVersion)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().asFile
            .resolve("io/github/menjoo/cucumberkmp/gradle/Version.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            // Generated by the build. Do not edit.
            package io.github.menjoo.cucumberkmp.gradle

            internal const val CUCUMBER_KMP_VERSION: String = "$pluginVersion"
            """.trimIndent() + "\n",
        )
    }
}

kotlin.sourceSets.named("main") {
    kotlin.srcDir(generateVersionConstant)
}

gradlePlugin {
    website = "https://github.com/menjoo/cucumber-kmp"
    vcsUrl = "https://github.com/menjoo/cucumber-kmp.git"
    plugins {
        create("cucumberKmp") {
            id = "io.github.menjoo.cucumberkmp"
            implementationClass = "io.github.menjoo.cucumberkmp.gradle.CucumberKmpPlugin"
            displayName = "cucumber-kmp"
            description = "Generates Kotlin Multiplatform tests from Gherkin .feature files."
            tags = listOf("cucumber", "gherkin", "bdd", "kotlin-multiplatform", "testing")
        }
    }
}

tasks.test {
    useJUnitPlatform()
}
