package io.github.menjoo.cucumberkmp.gradle

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import io.github.menjoo.cucumberkmp.core.SourceLocation
import io.github.menjoo.cucumberkmp.core.gherkin.DataTable
import io.github.menjoo.cucumberkmp.core.gherkin.DocString
import io.github.menjoo.cucumberkmp.core.gherkin.GherkinParser
import io.github.menjoo.cucumberkmp.core.gherkin.Pickle
import io.github.menjoo.cucumberkmp.core.gherkin.PickleCompiler
import io.github.menjoo.cucumberkmp.core.gherkin.PickleStep
import io.github.menjoo.cucumberkmp.core.gherkin.TableRow

/**
 * Turns one `.feature` file into a Kotlin test class.
 *
 * The scenarios are compiled to [Pickle]s at build time and **embedded as constructor calls**, not
 * as the original text. That is the whole trick: Kotlin/Native and Wasm cannot read a file at
 * runtime, so the feature has to arrive as compiled code. See ARCHITECTURE.md §4a.
 *
 * Pure by design — it takes source text and returns source text — so the interesting behaviour is
 * testable without running Gradle.
 */
public object FeatureTestGenerator {

    /**
     * @param path the feature's path, as it should appear in failure messages
     * @param source the feature file's contents
     * @param packageName package for the generated test class
     * @param stepRegistry a fully-qualified expression evaluating to a `StepRegistryFactory`
     * @param tagFilter an optional tag expression restricting which scenarios are generated
     */
    public fun generate(
        path: String,
        source: String,
        packageName: String,
        stepRegistry: String,
        tagFilter: String? = null,
    ): GeneratedFeatureTest {
        val document = GherkinParser.parse(path, source)
        val pickles = PickleCompiler.compile(document)

        val className = testClassName(path)
        val type = TypeSpec.classBuilder(className)
            .addKdoc(
                "Generated from %L. Do not edit — change the feature file instead.\n",
                path,
            )

        val companion = TypeSpec.companionObjectBuilder()
            .addModifiers(KModifier.PRIVATE)
            .addProperty(
                PropertySpec.builder("RUNNER", CUCUMBER_RUNNER, KModifier.PRIVATE)
                    .initializer("%T(%L)", CUCUMBER_RUNNER, stepRegistry)
                    .build(),
            )

        val usedNames = mutableSetOf<String>()
        var generated = 0

        pickles.forEachIndexed { index, pickle ->
            val pickleProperty = "PICKLE_$index"
            companion.addProperty(
                PropertySpec.builder(pickleProperty, PICKLE, KModifier.PRIVATE)
                    .initializer(pickleCode(pickle))
                    .build(),
            )

            val functionName = uniqueFunctionName(pickle.name, index, usedNames)
            val function = FunSpec.builder(functionName)
                .addAnnotation(TEST)
                .returns(TEST_RESULT)
                .addKdoc("%L\n", pickle.name.ifEmpty { "(unnamed scenario)" })

            if (tagFilter != null && !matchesFilter(pickle, tagFilter)) {
                // Reported as skipped rather than omitted, so a filtered run still shows what
                // exists. See ARCHITECTURE.md §9.
                function.addAnnotation(IGNORE)
            }

            // Must return the runTest result: on JS and Wasm a suspending test is only awaited if
            // its TestResult is handed back to the framework.
            function.addStatement("return %M { RUNNER.runOrThrow(%N) }", RUN_TEST, pickleProperty)
            type.addFunction(function.build())
            generated++
        }

        type.addType(companion.build())

        val file = FileSpec.builder(packageName, className)
            .addFileComment("Generated by the cucumber-kmp Gradle plugin from %L. Do not edit.", path)
            .addType(type.build())
            .build()

        return GeneratedFeatureTest(
            className = className,
            relativePath = packageName.replace('.', '/') + "/$className.kt",
            code = file.toString(),
            scenarioCount = generated,
        )
    }

    private fun matchesFilter(pickle: Pickle, tagFilter: String): Boolean =
        io.github.menjoo.cucumberkmp.core.tag.TagExpressionParser.parse(tagFilter).evaluate(pickle.tags)

    // ------------------------------------------------------------------- naming

    /** `shopping cart.feature` becomes `ShoppingCartFeatureTest`. */
    internal fun testClassName(path: String): String {
        val base = path.substringAfterLast('/').removeSuffix(".feature")
        return base.split(Regex("[^A-Za-z0-9]+"))
            .filter { it.isNotEmpty() }
            .joinToString("") { part -> part.replaceFirstChar { it.uppercaseChar() } }
            .ifEmpty { "Feature" }
            .plus("FeatureTest")
    }

    /**
     * Builds a valid Kotlin identifier from a scenario name.
     *
     * Backticked names with spaces would read better, but they are not portable — Android's dexer
     * and some JS toolchains reject them — so the human-readable name goes in the KDoc and the
     * failure message instead, both of which already carry it.
     */
    internal fun uniqueFunctionName(scenarioName: String, index: Int, used: MutableSet<String>): String {
        val sanitized = scenarioName
            .split(Regex("[^A-Za-z0-9]+"))
            .filter { it.isNotEmpty() }
            .mapIndexed { position, word ->
                if (position == 0) word.replaceFirstChar { it.lowercaseChar() }
                else word.replaceFirstChar { it.uppercaseChar() }
            }
            .joinToString("")
            .ifEmpty { "scenario" }

        val base = if (sanitized.first().isDigit()) "scenario$sanitized" else sanitized
        // Outline rows share a name, and two scenarios may legitimately be called the same thing.
        var candidate = base
        var suffix = 2
        while (!used.add(candidate)) {
            candidate = "$base$suffix"
            suffix++
        }
        return candidate
    }

    // ------------------------------------------------------------------ embedding

    private fun pickleCode(pickle: Pickle): CodeBlock {
        val steps = CodeBlock.builder()
        for (step in pickle.steps) {
            steps.add("%L,\n", stepCode(step))
        }
        return CodeBlock.builder()
            .add("%T(\n", PICKLE).indent()
            .add("name = %S,\n", pickle.name)
            .add("language = %S,\n", pickle.language)
            .add("location = %L,\n", locationCode(pickle.location))
            .add("tags = listOf(%L),\n", pickle.tags.joinToString { "\"$it\"" })
            .add("steps = listOf(\n").indent()
            .add(steps.build())
            .unindent().add("),\n")
            .unindent().add(")")
            .build()
    }

    private fun stepCode(step: PickleStep): CodeBlock {
        val builder = CodeBlock.builder()
            .add("%T(\n", PICKLE_STEP).indent()
            .add("text = %S,\n", step.text)
            .add("type = %T.%L,\n", STEP_KEYWORD_TYPE, step.type.name)
            .add("location = %L,\n", locationCode(step.location))
        step.dataTable?.let { builder.add("dataTable = %L,\n", dataTableCode(it)) }
        step.docString?.let { builder.add("docString = %L,\n", docStringCode(it)) }
        return builder.unindent().add(")").build()
    }

    private fun dataTableCode(table: DataTable): CodeBlock {
        val rows = CodeBlock.builder()
        for (row in table.rows) rows.add("%L,\n", rowCode(row))
        return CodeBlock.builder()
            .add("%T(\n", DATA_TABLE).indent()
            .add("location = %L,\n", locationCode(table.location))
            .add("rows = listOf(\n").indent()
            .add(rows.build())
            .unindent().add("),\n")
            .unindent().add(")")
            .build()
    }

    private fun rowCode(row: TableRow): CodeBlock {
        val builder = CodeBlock.builder()
            .add("%T(%L, listOf(", TABLE_ROW, locationCode(row.location))
        row.cells.forEachIndexed { index, cell ->
            if (index > 0) builder.add(", ")
            builder.add("%T(%L, %S)", TABLE_CELL, locationCode(cell.location), cell.value)
        }
        return builder.add("))").build()
    }

    private fun docStringCode(docString: DocString): CodeBlock =
        CodeBlock.builder()
            .add("%T(\n", DOC_STRING).indent()
            .add("location = %L,\n", locationCode(docString.location))
            .add("content = %S,\n", docString.content)
            .add("mediaType = %L,\n", docString.mediaType?.let { "\"$it\"" } ?: "null")
            .add("delimiter = %S,\n", docString.delimiter)
            .unindent().add(")")
            .build()

    private fun locationCode(location: SourceLocation): CodeBlock =
        CodeBlock.of("%T(%S, %L, %L)", SOURCE_LOCATION, location.path, location.line, location.column)

    private const val CORE = "io.github.menjoo.cucumberkmp.core"
    private val SOURCE_LOCATION = ClassName(CORE, "SourceLocation")
    private val PICKLE = ClassName("$CORE.gherkin", "Pickle")
    private val PICKLE_STEP = ClassName("$CORE.gherkin", "PickleStep")
    private val STEP_KEYWORD_TYPE = ClassName("$CORE.gherkin", "StepKeywordType")
    private val DATA_TABLE = ClassName("$CORE.gherkin", "DataTable")
    private val TABLE_ROW = ClassName("$CORE.gherkin", "TableRow")
    private val TABLE_CELL = ClassName("$CORE.gherkin", "TableCell")
    private val DOC_STRING = ClassName("$CORE.gherkin", "DocString")
    private val CUCUMBER_RUNNER = ClassName("$CORE.runner", "CucumberRunner")
    private val TEST = ClassName("kotlin.test", "Test")
    private val IGNORE = ClassName("kotlin.test", "Ignore")
    private val TEST_RESULT = ClassName("kotlinx.coroutines.test", "TestResult")
    private val RUN_TEST = MemberName("kotlinx.coroutines.test", "runTest")
}

/** One generated test class. */
public data class GeneratedFeatureTest(
    public val className: String,
    public val relativePath: String,
    public val code: String,
    public val scenarioCount: Int,
)
